[package]
name = "prop-engine-sb-contracts"
version = "0.1.0"
edition = "2021"

[features]
account-registration = []
payment-order = []
trader-account-creation = []
trader-account-status-update = []
account-balance-update = []
trading-scenario-update = []
metatrader-scenario-update = []
trader-account-open-position = []
account-kyc-update = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
my-service-bus-abstractions = { tag = "0.1.1", git = "https://github.com/MyJetTools/my-service-bus-abstractions.git" }
my-service-bus-macros = { tag = "0.1.0", git = "https://github.com/MyJetTools/my-service-bus-macros.git" }

prost = "*"
prost-types = "*"
